version: "3"

services:
  xray:
    image: ghcr.io/getimages/xray:1.6.0
    container_name: xray_bridge
    restart: always
    environment:
      - "XRAY_VMESS_AEAD_FORCED=false"
      - "xray.vmess.aead.forced=false"
    ports:
      - 127.0.0.1:${HTTP_PORT:-2010}:2010
      - 127.0.0.1:${HTTP_PORT:-2010}:2010/udp
      - 127.0.0.1:${HTTP_PORT:-2110}:2110
      - 127.0.0.1:${HTTP_PORT:-2110}:2110/udp
      - ${SHADOWSOCKS_PORT:-2210}:2210
      - ${SHADOWSOCKS_PORT:-2210}:2210/udp
      - ${VMESS_PORT:-2310}:2310
      - ${VMESS_PORT:-2310}:2310/udp
    volumes:
      - ./config/:/etc/xray/
      - ./logs:/var/log/xray/
